// File generated by the Nog compiler.
// https://github.com/nog-lang/nog

#include "main.h"

static unsigned int hello();
static char A();

static unsigned int hello()
{
	return -2;
}

int main()
{
	return 0;
}

static char A()
{
	return 65;
}
